In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('datasets/results.csv', parse_dates=["date"])

df.shape

(49498, 9)

In [4]:
df.dtypes

date          datetime64[ns]
home_team             object
away_team             object
home_score           float64
away_score           float64
tournament            object
city                  object
country               object
neutral                 bool
dtype: object

In [5]:
df.head()

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False

In [6]:
df.isna().sum()

date           0
home_team      0
away_team      0
home_score    11
away_score    11
tournament     0
city           0
country        0
neutral        0
dtype: int64

In [7]:
df["date"].min()

Timestamp('1872-11-30 00:00:00')

In [8]:
df["date"].max()

Timestamp('2026-07-06 00:00:00')

In [9]:
df["tournament"].value_counts().head(15)

tournament
Friendly                                18388
FIFA World Cup qualification             8771
UEFA Euro qualification                  2824
African Cup of Nations qualification     2327
FIFA World Cup                           1057
Copa América                              869
African Cup of Nations                    845
AFC Asian Cup qualification               829
UEFA Nations League                       658
CECAFA Cup                                620
CFU Caribbean Cup qualification           606
Merdeka Tournament                        599
British Home Championship                 523
CONCACAF Nations League                   422
AFC Asian Cup                             421
Name: count, dtype: int64

In [10]:
pd.concat([df["home_team"], df["away_team"]]).nunique()

336

In [11]:
df[df["home_score"].isna()]

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
49487,2026-07-02,Spain,Austria,NaN,NaN,FIFA World Cup,Inglewood,United States,True
49488,2026-07-02,Portugal,Croatia,NaN,NaN,FIFA World Cup,Toronto,Canada,True
49489,2026-07-02,Switzerland,Algeria,NaN,NaN,FIFA World Cup,Vancouver,Canada,True
49490,2026-07-03,Australia,Egypt,NaN,NaN,FIFA World Cup,Arlington,United States,True
49491,2026-07-03,Argentina,Cape Verde,NaN,NaN,FIFA World Cup,Miami Gardens,United States,True
49492,2026-07-03,Colombia,Ghana,NaN,NaN,FIFA World Cup,Kansas City,United States,True
49493,2026-07-04,Canada,Morocco,NaN,NaN,FIFA World Cup,Houston,United States,True
49494,2026-07-04,Paraguay,France,NaN,NaN,FIFA World Cup,Philadelphia,United States,True
49495,2026-07-05,Brazil,Norway,NaN,NaN,FIFA World Cup,East Rutherford,United States,True
49496,2026-07-05,Mexico,England,NaN,NaN,FIFA World Cup,Mexico City,Mexico,False
49497,2026-07-06,United States,Belgium,NaN,NaN,FIFA World Cup,Seattle,United States,False

In [19]:
played = df[df["home_score"].notna()].copy()

In [17]:
played["home_score"] = played["home_score"].astype(int)
played["away_score"] = played["away_score"].astype(int)

In [20]:
modern = played[played["date"] >= "1990-01-01"]

In [21]:
upcoming = df[df["home_score"].isna()].copy()